targets:
  - address: "https://en.wikipedia.org/wiki/Special:Statistics"
    decimal_point_separator: "."
    thousands_separator: ","
    metrics:
      - name: wikipedia_articles_total
        type: gauge
        help: "Total of articles available at Wikipedia"
        selector: "//div[@id='mw-content-text']//tr[@class='mw-statistics-articles']/td[@class='mw-statistics-numbers']/text()"
        labels:
          language: english
      - name: wikipedia_uploaded_files_total
        type: gauge
        help: "Total of uploaded files at Wikipedia"
        selector: "//div[@id='mw-content-text']//tr[@class='mw-statistics-files']/td[@class='mw-statistics-numbers']/text()"
        labels:
          language: english
  - address: "https://fr.wikipedia.org/wiki/Special:Statistics"
    decimal_point_separator: ","
    thousands_separator: " "
    metrics:
      - name: wikipedia_articles_total
        type: gauge
        help: "Total of articles available at Wikipedia"
        selector: "//div[@id='mw-content-text']//tr[@class='mw-statistics-articles']/td[@class='mw-statistics-numbers']/text()"
        labels:
          language: french
global_config:
  port: 9883
  metric_name_prefix: "htmlexporter_"
